const getRandomIncome = (min, max) => {
  const isNegative = Math.random() < 0.2;
  const randomValue = Math.floor(Math.random() * (max - min + 1)) + min;
  return isNegative ? -randomValue : randomValue;
};
function generatePhoneNumber() {
  const randomDigits = Math.floor(10000000 + Math.random() * 90000000);
  return `074${randomDigits}`;
}

export const chartNetIncome = {
  icon: "ph-wallet",
  title: "Net Income",
  dataKey: "income",
  color: "#6193ff",
  viewAll: "All Income",
  timeline: {
    weekly: [
      { name: "Sun", income: getRandomIncome(300, 700) },
      { name: "Mon", income: getRandomIncome(300, 700) },
      { name: "Tue", income: getRandomIncome(300, 700) },
      { name: "Wed", income: getRandomIncome(300, 700) },
      { name: "Thu", income: getRandomIncome(300, 700) },
      { name: "Fri", income: getRandomIncome(300, 700) },
      { name: "Sat", income: getRandomIncome(300, 700) },
    ],
    monthly: [
      { name: "Jan", income: getRandomIncome(2000, 4000) },
      { name: "Feb", income: getRandomIncome(2000, 4000) },
      { name: "Mar", income: getRandomIncome(2000, 4000) },
      { name: "Apr", income: getRandomIncome(2000, 4000) },
      { name: "May", income: getRandomIncome(2000, 4000) },
      { name: "Jun", income: getRandomIncome(2000, 4000) },
      { name: "Jul", income: getRandomIncome(2000, 4000) },
      { name: "Aug", income: getRandomIncome(2000, 4000) },
      { name: "Sep", income: getRandomIncome(2000, 4000) },
      { name: "Oct", income: getRandomIncome(2000, 4000) },
      { name: "Nov", income: getRandomIncome(2000, 4000) },
      { name: "Dec", income: getRandomIncome(2000, 4000) },
    ],
    yearly: [
      { name: "2014", income: getRandomIncome(30000, 50000) },
      { name: "2015", income: getRandomIncome(30000, 50000) },
      { name: "2016", income: getRandomIncome(30000, 50000) },
      { name: "2017", income: getRandomIncome(30000, 50000) },
      { name: "2018", income: getRandomIncome(30000, 50000) },
      { name: "2019", income: getRandomIncome(30000, 50000) },
      { name: "2020", income: getRandomIncome(30000, 50000) },
      { name: "2021", income: getRandomIncome(30000, 50000) },
      { name: "2022", income: getRandomIncome(30000, 50000) },
      { name: "2023", income: getRandomIncome(30000, 50000) },
    ],
  },
};

export const chartNetUser = {
  icon: "ph-users",
  title: "All Users",
  dataKey: "users",
  color: "#e99b26",
  viewAll: "All Users",
  timeline: {
    weekly: [
      { name: "Sun", users: getRandomIncome(300, 700) },
      { name: "Mon", users: getRandomIncome(300, 700) },
      { name: "Tue", users: getRandomIncome(300, 700) },
      { name: "Wed", users: getRandomIncome(300, 700) },
      { name: "Thu", users: getRandomIncome(300, 700) },
      { name: "Fri", users: getRandomIncome(300, 700) },
      { name: "Sat", users: getRandomIncome(300, 700) },
    ],
    monthly: [
      { name: "Jan", users: getRandomIncome(2000, 4000) },
      { name: "Feb", users: getRandomIncome(2000, 4000) },
      { name: "Mar", users: getRandomIncome(2000, 4000) },
      { name: "Apr", users: getRandomIncome(2000, 4000) },
      { name: "May", users: getRandomIncome(2000, 4000) },
      { name: "Jun", users: getRandomIncome(2000, 4000) },
      { name: "Jul", users: getRandomIncome(2000, 4000) },
      { name: "Aug", users: getRandomIncome(2000, 4000) },
      { name: "Sep", users: getRandomIncome(2000, 4000) },
      { name: "Oct", users: getRandomIncome(2000, 4000) },
      { name: "Nov", users: getRandomIncome(2000, 4000) },
      { name: "Dec", users: getRandomIncome(2000, 4000) },
    ],
    yearly: [
      { name: "2014", users: getRandomIncome(30000, 50000) },
      { name: "2015", users: getRandomIncome(30000, 50000) },
      { name: "2016", users: getRandomIncome(30000, 50000) },
      { name: "2017", users: getRandomIncome(30000, 50000) },
      { name: "2018", users: getRandomIncome(30000, 50000) },
      { name: "2019", users: getRandomIncome(30000, 50000) },
      { name: "2020", users: getRandomIncome(30000, 50000) },
      { name: "2021", users: getRandomIncome(30000, 50000) },
      { name: "2022", users: getRandomIncome(30000, 50000) },
      { name: "2023", users: getRandomIncome(30000, 50000) },
    ],
  },
};

export const chartNetInsurance = {
  icon: "ph-umbrella",
  title: "Net Insurance",
  dataKey: "insurance",
  color: "#4bb592",
  viewAll: "All insurance",
  timeline: {
    weekly: [
      { name: "Sun", insurance: getRandomIncome(300, 700) },
      { name: "Mon", insurance: getRandomIncome(300, 700) },
      { name: "Tue", insurance: getRandomIncome(300, 700) },
      { name: "Wed", insurance: getRandomIncome(300, 700) },
      { name: "Thu", insurance: getRandomIncome(300, 700) },
      { name: "Fri", insurance: getRandomIncome(300, 700) },
      { name: "Sat", insurance: getRandomIncome(300, 700) },
    ],
    monthly: [
      { name: "Jan", insurance: getRandomIncome(2000, 4000) },
      { name: "Feb", insurance: getRandomIncome(2000, 4000) },
      { name: "Mar", insurance: getRandomIncome(2000, 4000) },
      { name: "Apr", insurance: getRandomIncome(2000, 4000) },
      { name: "May", insurance: getRandomIncome(2000, 4000) },
      { name: "Jun", insurance: getRandomIncome(2000, 4000) },
      { name: "Jul", insurance: getRandomIncome(2000, 4000) },
      { name: "Aug", insurance: getRandomIncome(2000, 4000) },
      { name: "Sep", insurance: getRandomIncome(2000, 4000) },
      { name: "Oct", insurance: getRandomIncome(2000, 4000) },
      { name: "Nov", insurance: getRandomIncome(2000, 4000) },
      { name: "Dec", insurance: getRandomIncome(2000, 4000) },
    ],
    yearly: [
      { name: "2014", insurance: getRandomIncome(30000, 50000) },
      { name: "2015", insurance: getRandomIncome(30000, 50000) },
      { name: "2016", insurance: getRandomIncome(30000, 50000) },
      { name: "2017", insurance: getRandomIncome(30000, 50000) },
      { name: "2018", insurance: getRandomIncome(30000, 50000) },
      { name: "2019", insurance: getRandomIncome(30000, 50000) },
      { name: "2020", insurance: getRandomIncome(30000, 50000) },
      { name: "2021", insurance: getRandomIncome(30000, 50000) },
      { name: "2022", insurance: getRandomIncome(30000, 50000) },
      { name: "2023", insurance: getRandomIncome(30000, 50000) },
    ],
  },
};

export const chartNetExpense = {
  icon: "ph-clipboard-text",
  title: "Net Expense",
  dataKey: "expense",
  color: "#FFBB28",
  viewAll: "All expense",
  timeline: {
    weekly: [
      { name: "Sun", expense: getRandomIncome(300, 700) },
      { name: "Mon", expense: getRandomIncome(300, 700) },
      { name: "Tue", expense: getRandomIncome(300, 700) },
      { name: "Wed", expense: getRandomIncome(300, 700) },
      { name: "Thu", expense: getRandomIncome(300, 700) },
      { name: "Fri", expense: getRandomIncome(300, 700) },
      { name: "Sat", expense: getRandomIncome(300, 700) },
    ],
    monthly: [
      { name: "Jan", expense: getRandomIncome(2000, 4000) },
      { name: "Feb", expense: getRandomIncome(2000, 4000) },
      { name: "Mar", expense: getRandomIncome(2000, 4000) },
      { name: "Apr", expense: getRandomIncome(2000, 4000) },
      { name: "May", expense: getRandomIncome(2000, 4000) },
      { name: "Jun", expense: getRandomIncome(2000, 4000) },
      { name: "Jul", expense: getRandomIncome(2000, 4000) },
      { name: "Aug", expense: getRandomIncome(2000, 4000) },
      { name: "Sep", expense: getRandomIncome(2000, 4000) },
      { name: "Oct", expense: getRandomIncome(2000, 4000) },
      { name: "Nov", expense: getRandomIncome(2000, 4000) },
      { name: "Dec", expense: getRandomIncome(2000, 4000) },
    ],
    yearly: [
      { name: "2014", expense: getRandomIncome(30000, 50000) },
      { name: "2015", expense: getRandomIncome(30000, 50000) },
      { name: "2016", expense: getRandomIncome(30000, 50000) },
      { name: "2017", expense: getRandomIncome(30000, 50000) },
      { name: "2018", expense: getRandomIncome(30000, 50000) },
      { name: "2019", expense: getRandomIncome(30000, 50000) },
      { name: "2020", expense: getRandomIncome(30000, 50000) },
      { name: "2021", expense: getRandomIncome(30000, 50000) },
      { name: "2022", expense: getRandomIncome(30000, 50000) },
      { name: "2023", expense: getRandomIncome(30000, 50000) },
    ],
  },
};

export const AreaChartRepeatCustomer = {
  icon: "ph-users",
  title: "Repeat Insurance Rate",
  dataKey: "repeatUsers",
  timeline: {
    weekly: [
      { name: "Sun", repeatUsers: getRandomIncome(300, 700) },
      { name: "Mon", repeatUsers: getRandomIncome(300, 700) },
      { name: "Tue", repeatUsers: getRandomIncome(300, 700) },
      { name: "Wed", repeatUsers: getRandomIncome(300, 700) },
      { name: "Thu", repeatUsers: getRandomIncome(300, 700) },
      { name: "Fri", repeatUsers: getRandomIncome(300, 700) },
      { name: "Sat", repeatUsers: getRandomIncome(300, 700) },
    ],
    monthly: [
      { name: "Jan", repeatUsers: getRandomIncome(2000, 4000) },
      { name: "Feb", repeatUsers: getRandomIncome(2000, 4000) },
      { name: "Mar", repeatUsers: getRandomIncome(2000, 4000) },
      { name: "Apr", repeatUsers: getRandomIncome(2000, 4000) },
      { name: "May", repeatUsers: getRandomIncome(2000, 4000) },
      { name: "Jun", repeatUsers: getRandomIncome(2000, 4000) },
      { name: "Jul", repeatUsers: getRandomIncome(2000, 4000) },
      { name: "Aug", repeatUsers: getRandomIncome(2000, 4000) },
      { name: "Sep", repeatUsers: getRandomIncome(2000, 4000) },
      { name: "Oct", repeatUsers: getRandomIncome(2000, 4000) },
      { name: "Nov", repeatUsers: getRandomIncome(2000, 4000) },
      { name: "Dec", repeatUsers: getRandomIncome(2000, 4000) },
    ],
    yearly: [
      { name: "2014", repeatUsers: getRandomIncome(30000, 50000) },
      { name: "2015", repeatUsers: getRandomIncome(30000, 50000) },
      { name: "2016", repeatUsers: getRandomIncome(30000, 50000) },
      { name: "2017", repeatUsers: getRandomIncome(30000, 50000) },
      { name: "2018", repeatUsers: getRandomIncome(30000, 50000) },
      { name: "2019", repeatUsers: getRandomIncome(30000, 50000) },
      { name: "2020", repeatUsers: getRandomIncome(30000, 50000) },
      { name: "2021", repeatUsers: getRandomIncome(30000, 50000) },
      { name: "2022", repeatUsers: getRandomIncome(30000, 50000) },
      { name: "2023", repeatUsers: getRandomIncome(30000, 50000) },
    ],
  },
};

export const dummyAllInsurance = [
  {
    id: 1,
    FullName: "Snow Jon",
    age: 14,
    phone: generatePhoneNumber(),
    category: "Bronze",
    status: "accepted",
  },
  {
    id: 2,
    FullName: "Lannister Cersei",
    age: 31,
    phone: generatePhoneNumber(),
    category: "Gold",
    status: "rejected",
  },
  {
    id: 3,
    FullName: "Lannister Jaime",
    age: 31,
    phone: generatePhoneNumber(),
    category: "Silver",
    status: "pending",
  },
  {
    id: 4,
    FullName: "Stark Arya",
    age: 11,
    phone: generatePhoneNumber(),
    category: "Bronze",
    status: "accepted",
  },
  {
    id: 5,
    FullName: "Targaryen Daenerys",
    age: null,
    phone: generatePhoneNumber(),
    category: "Platinum",
    status: "pending",
  },
  {
    id: 6,
    FullName: "Melisandre",
    age: 150,
    phone: generatePhoneNumber(),
    category: "Gold",
    status: "rejected",
  },
  {
    id: 7,
    FullName: "Clifford Ferrara",
    age: 44,
    phone: generatePhoneNumber(),
    category: "Silver",
    status: "accepted",
  },
  {
    id: 8,
    FullName: "Frances Rossini",
    age: 36,
    phone: generatePhoneNumber(),
    category: "Platinum",
    status: "rejected",
  },
  {
    id: 9,
    FullName: "Roxie Harvey",
    age: 65,
    phone: generatePhoneNumber(),
    category: "Bronze",
    status: "pending",
  },
  {
    id: 10,
    FullName: "Snow Jon",
    age: 14,
    phone: generatePhoneNumber(),
    category: "Silver",
    status: "accepted",
  },
  {
    id: 11,
    FullName: "Lannister Cersei",
    age: 31,
    phone: generatePhoneNumber(),
    category: "Gold",
    status: "rejected",
  },
  {
    id: 12,
    FullName: "Lannister Jaime",
    age: 31,
    phone: generatePhoneNumber(),
    category: "Bronze",
    status: "accepted",
  },
  {
    id: 13,
    FullName: "Stark Arya",
    age: 11,
    phone: generatePhoneNumber(),
    category: "Silver",
    status: "pending",
  },
  {
    id: 14,
    FullName: "Targaryen Daenerys",
    age: null,
    phone: generatePhoneNumber(),
    category: "Gold",
    status: "accepted",
  },
  {
    id: 15,
    FullName: "Melisandre",
    age: 150,
    phone: generatePhoneNumber(),
    category: "Bronze",
    status: "rejected",
  },
  {
    id: 16,
    FullName: "Clifford Ferrara",
    age: 44,
    phone: generatePhoneNumber(),
    category: "Silver",
    status: "pending",
  },
  {
    id: 17,
    FullName: "Frances Rossini",
    age: 36,
    phone: generatePhoneNumber(),
    category: "Platinum",
    status: "accepted",
  },
  {
    id: 18,
    FullName: "Roxie Harvey",
    age: 65,
    phone: generatePhoneNumber(),
    category: "Gold",
    status: "rejected",
  },
  {
    id: 19,
    FullName: "Snow Jon",
    age: 14,
    phone: generatePhoneNumber(),
    category: "Bronze",
    status: "accepted",
  },
  {
    id: 20,
    FullName: "Lannister Cersei",
    age: 31,
    phone: generatePhoneNumber(),
    category: "Silver",
    status: "pending",
  },
  {
    id: 21,
    FullName: "Lannister Jaime",
    age: 31,
    phone: generatePhoneNumber(),
    category: "Platinum",
    status: "rejected",
  },
  {
    id: 22,
    FullName: "Stark Arya",
    age: 11,
    phone: generatePhoneNumber(),
    category: "Gold",
    status: "accepted",
  },
  {
    id: 23,
    FullName: "Targaryen Daenerys",
    age: null,
    phone: generatePhoneNumber(),
    category: "Bronze",
    status: "rejected",
  },
  {
    id: 24,
    FullName: "Melisandre",
    age: 150,
    phone: generatePhoneNumber(),
    category: "Silver",
    status: "pending",
  },
  {
    id: 25,
    FullName: "Clifford Ferrara",
    age: 44,
    phone: generatePhoneNumber(),
    category: "Gold",
    status: "accepted",
  },
  {
    id: 26,
    FullName: "Frances Rossini",
    age: 36,
    phone: generatePhoneNumber(),
    category: "Bronze",
    status: "rejected",
  },
  {
    id: 27,
    FullName: "Roxie Harvey",
    age: 65,
    phone: generatePhoneNumber(),
    category: "Platinum",
    status: "pending",
  },
  {
    id: 28,
    FullName: "Snow Jon",
    age: 14,
    phone: generatePhoneNumber(),
    category: "Gold",
    status: "accepted",
  },
  {
    id: 29,
    FullName: "Lannister Cersei",
    age: 31,
    phone: generatePhoneNumber(),
    category: "Silver",
    status: "rejected",
  },
  {
    id: 30,
    FullName: "Lannister Jaime",
    age: 31,
    phone: generatePhoneNumber(),
    category: "Bronze",
    status: "pending",
  },
  {
    id: 31,
    FullName: "Stark Arya",
    age: 11,
    phone: generatePhoneNumber(),
    category: "Platinum",
    status: "accepted",
  },
  {
    id: 32,
    FullName: "Targaryen Daenerys",
    age: null,
    phone: generatePhoneNumber(),
    category: "Gold",
    status: "rejected",
  },
  {
    id: 33,
    FullName: "Melisandre",
    age: 150,
    phone: generatePhoneNumber(),
    category: "Bronze",
    status: "pending",
  },
  {
    id: 34,
    FullName: "Clifford Ferrara",
    age: 44,
    phone: generatePhoneNumber(),
    category: "Silver",
    status: "accepted",
  },
  {
    id: 35,
    FullName: "Frances Rossini",
    age: 36,
    phone: generatePhoneNumber(),
    category: "Platinum",
    status: "rejected",
  },
  {
    id: 36,
    FullName: "Roxie Harvey",
    age: 65,
    phone: generatePhoneNumber(),
    category: "Gold",
    status: "pending",
  },
  {
    id: 37,
    FullName: "Snow Jon",
    age: 14,
    phone: generatePhoneNumber(),
    category: "Bronze",
    status: "accepted",
  },
  {
    id: 38,
    FullName: "Lannister Cersei",
    age: 31,
    phone: generatePhoneNumber(),
    category: "Silver",
    status: "rejected",
  },
  {
    id: 39,
    FullName: "Lannister Jaime",
    age: 31,
    phone: generatePhoneNumber(),
    category: "Gold",
    status: "pending",
  },
  {
    id: 40,
    FullName: "Stark Arya",
    age: 11,
    phone: generatePhoneNumber(),
    category: "Bronze",
    status: "accepted",
  },
  {
    id: 41,
    FullName: "Targaryen Daenerys",
    age: null,
    phone: generatePhoneNumber(),
    category: "Platinum",
    status: "rejected",
  },
  {
    id: 42,
    FullName: "Melisandre",
    age: 150,
    phone: generatePhoneNumber(),
    category: "Silver",
    status: "pending",
  },
  {
    id: 43,
    FullName: "Clifford Ferrara",
    age: 44,
    phone: generatePhoneNumber(),
    category: "Gold",
    status: "accepted",
  },
  {
    id: 44,
    FullName: "Frances Rossini",
    age: 36,
    phone: generatePhoneNumber(),
    category: "Bronze",
    status: "rejected",
  },
  {
    id: 45,
    FullName: "Roxie Harvey",
    age: 65,
    phone: generatePhoneNumber(),
    category: "Silver",
    status: "pending",
  },
  {
    id: 46,
    FullName: "Snow Jon",
    age: 14,
    phone: generatePhoneNumber(),
    category: "Platinum",
    status: "accepted",
  },
  {
    id: 47,
    FullName: "Lannister Cersei",
    age: 31,
    phone: generatePhoneNumber(),
    category: "Gold",
    status: "rejected",
  },
  {
    id: 48,
    FullName: "Lannister Jaime",
    age: 31,
    phone: generatePhoneNumber(),
    category: "Bronze",
    status: "pending",
  },
  {
    id: 49,
    FullName: "Stark Arya",
    age: 11,
    phone: generatePhoneNumber(),
    category: "Silver",
    status: "accepted",
  },
  {
    id: 50,
    FullName: "Targaryen Daenerys",
    age: null,
    phone: generatePhoneNumber(),
    category: "Gold",
    status: "rejected",
  },
  {
    id: 51,
    FullName: "Melisandre",
    age: 150,
    phone: generatePhoneNumber(),
    category: "Bronze",
    status: "pending",
  },
  {
    id: 52,
    FullName: "Clifford Ferrara",
    age: 44,
    phone: generatePhoneNumber(),
    category: "Silver",
    status: "accepted",
  },
  {
    id: 53,
    FullName: "Frances Rossini",
    age: 36,
    phone: generatePhoneNumber(),
    category: "Platinum",
    status: "rejected",
  },
  {
    id: 54,
    FullName: "Roxie Harvey",
    age: 65,
    phone: generatePhoneNumber(),
    category: "Gold",
    status: "pending",
  },
];
export const insuranceCategory = [
  { value: "", label: "Insurance Category" },
  { value: "Bronze", label: "Bronze" },
  { value: "Silver", label: "Silver" },
  { value: "Gold", label: "Gold" },
  { value: "Platinum", label: "Platinum" },
];
