// dummyNotifications.js
const dummyNotifications = [
  {
    id: 1,
    title: "You got a mail",
    message: "Hello! Hope you are doing well. I am here to inform you.",
    date: "8 August 2024",
    time: "6:06 PM",
    isRead: false,
  },
  {
    id: 2,
    title: "Meeting Reminder",
    message: "Don't forget about the meeting at 3 PM.",
    date: "9 August 2024",
    time: "2:00 PM",
    isRead: false,
  },
  {
    id: 3,
    title: "Task Deadline Approaching",
    message: "Your task is due tomorrow.",
    date: "10 August 2024",
    time: "10:00 AM",
    isRead: true,
  },
  {
    id: 4,
    title: "Project Update",
    message: "The project has been updated. Please review the changes.",
    date: "11 August 2024",
    time: "4:30 PM",
    isRead: false,
  },
  {
    id: 5,
    title: "New Assignment",
    message: "You have been assigned a new task. Check your dashboard.",
    date: "12 August 2024",
    time: "9:00 AM",
    isRead: false,
  },
  {
    id: 6,
    title: "System Maintenance",
    message: "System maintenance is scheduled for tonight at 12:00 AM.",
    date: "12 August 2024",
    time: "11:30 AM",
    isRead: true,
  },
  {
    id: 7,
    title: "Client Feedback Received",
    message: "New feedback has been received from the client.",
    date: "13 August 2024",
    time: "1:15 PM",
    isRead: false,
  },
  {
    id: 8,
    title: "HR Update",
    message: "Please review the latest HR policies in the employee portal.",
    date: "14 August 2024",
    time: "2:45 PM",
    isRead: false,
  },
  {
    id: 9,
    title: "Security Alert",
    message: "A security alert was triggered on your account.",
    date: "14 August 2024",
    time: "7:00 PM",
    isRead: true,
  },
  {
    id: 10,
    title: "Performance Review",
    message: "Your performance review is scheduled for next week.",
    date: "15 August 2024",
    time: "10:30 AM",
    isRead: false,
  },
  {
    id: 11,
    title: "Weekly Report Due",
    message: "Please submit your weekly report by end of day.",
    date: "15 August 2024",
    time: "5:00 PM",
    isRead: false,
  },
  {
    id: 12,
    title: "New Comment on Your Post",
    message: "Someone has commented on your post in the company forum.",
    date: "16 August 2024",
    time: "8:20 AM",
    isRead: false,
  },
  {
    id: 13,
    title: "Password Expiration",
    message: "Your password will expire in 3 days. Please update it.",
    date: "16 August 2024",
    time: "9:45 AM",
    isRead: false,
  },
  {
    id: 14,
    title: "New Message",
    message: "You have received a new message from HR.",
    date: "17 August 2024",
    time: "12:00 PM",
    isRead: true,
  },
  {
    id: 15,
    title: "Server Downtime Notification",
    message: "The server will be down for maintenance at 11:00 PM.",
    date: "17 August 2024",
    time: "2:00 PM",
    isRead: false,
  },
  {
    id: 16,
    title: "Expense Report Due",
    message: "Your expense report for last month is due tomorrow.",
    date: "18 August 2024",
    time: "3:30 PM",
    isRead: false,
  },
  {
    id: 17,
    title: "New Training Available",
    message: "A new training session is available. Please enroll.",
    date: "19 August 2024",
    time: "11:00 AM",
    isRead: false,
  },
  {
    id: 18,
    title: "Team Meeting Rescheduled",
    message: "The team meeting has been rescheduled to 4:00 PM.",
    date: "19 August 2024",
    time: "9:00 AM",
    isRead: false,
  },
  {
    id: 19,
    title: "Quarterly Goals",
    message: "Your quarterly goals have been updated. Please review them.",
    date: "20 August 2024",
    time: "4:00 PM",
    isRead: true,
  },
  {
    id: 20,
    title: "New Task Assigned",
    message: "You have been assigned a new task. Please check your tasks.",
    date: "21 August 2024",
    time: "10:15 AM",
    isRead: false,
  },
  {
    id: 21,
    title: "System Update",
    message: "A system update will occur at 11:00 PM tonight.",
    date: "21 August 2024",
    time: "3:00 PM",
    isRead: false,
  },
  {
    id: 22,
    title: "Project Milestone Reached",
    message: "Your project has reached a major milestone.",
    date: "22 August 2024",
    time: "9:30 AM",
    isRead: false,
  },
  {
    id: 23,
    title: "New Version Released",
    message: "A new version of the software is now available.",
    date: "23 August 2024",
    time: "11:45 AM",
    isRead: false,
  },
];

export default dummyNotifications;
